package com.alekseydorokhov.scouthelper.model.player;

public enum Position {
    GOALKEEPER,
    RIGHT_FULLBACK,
    LEFT_FULLBACK,
    CENTRAL_BACK,
    CENTRAL_BOXTOBOX_MIDFIELDER,
    CENTRAL_MIDFIELDER,
    CENTRAL_ATTACKING_MIDFIELDER,
    LEFT_MIDFIELDER,
    RIGHT_MIDFIELDER,
    LEFT_FORWARD,
    RIGHT_FORWARD,
    CENTRAL_FORWARD,
    DRAWN_STRIKER
}
